In [78]:
from solid import *
from solid.utils import *
import viewscad
import numpy as np

r = viewscad.Renderer()
#Z-X'-Z'' = 20-10-30:
def Rz(a: float):
    Rz = np.matrix([[np.cos(a), -np.sin(a),0],
         [np.sin(a), np.cos(a),0],
        [0,0,1]])
    return Rz

def Rx(a: float):
    Rx = np.matrix([[1,0,0],
                    [0, np.cos(a), -np.sin(a)],
                    [0, np.sin(a), np.cos(a)]])
    return Rx

def Ry(a: float):
    Ry = np.matrix([[np.cos(a),0,np.sin(a)],
                    [0, 1, 0],
                    [-np.sin(a), 0, np.cos(a)]])
    return Ry
def Rot_Trans(x: float,y:float,z:float,ax:float,ay:float,az:float):
    b = Rz(20)*Rx(10)*Rz(30)
    b = np.insert(b,[3],[[x],[y],[z]],axis=1)
    b = np.insert(np.transpose(b),[3],[[0],[0],[0],[1]],axis=1)
    b = np.transpose(b)

    return b
    

def q1a_t():
    b = Rz(20)*Rx(10)*Rz(30)
    bb = b.tolist()
    c = multmatrix(bb)(cube(1,center=True))
    
    #c = rotate([0,0,30])(rotate([10,0,0])(rotate([0,0,20])(cube(1,center=True))))
    r.render(c)
    print(scad_render(c))

    
def q1b_t():
    bb = Rot_Trans(5,5,5,20,10,30)
    bb = bb.tolist()
    c = multmatrix(bb)(cube(1,center=True))
    #c = translate([-5,-5,0])(rotate([0,0,30])(rotate([10,0,0])(rotate([0,0,20])(translate([5,5,0])(cube(1,center=True))))))
    r.render(c)
    print(scad_render(c))

def q1c_t():
    b = 0.5
    Sx = np.matrix([[1,0,0,0],[b,1,0,0],[b,0,1,0],[0,0,0,1]])
    Sx = Sx.tolist()
    Sy = np.matrix([[1,b,0,0],[0,1,0,0],[0,b,1,0],[0,0,0,1]])
    Sy = Sy.tolist()
    Sz = np.matrix([[1,0,b,0],[0,1,b,0],[0,0,1,0],[0,0,0,1]])
    Sz = Sz.tolist() 
    
    c = multmatrix(Sx)(cube(1,center=True))
  #  c = multmatrix(Sy)(cube(1,center=True))
  #  c = multmatrix(Sz)(cube(1,center=True))

    r.render(c)
q1c_t()




In [1]:
type(b[0][0])


NameError: name 'b' is not defined

In [ ]:
type([2,1,1])

In [12]:
type(aa)

list

In [ ]:
type(Rz[1][1])

In [ ]:
def aaaa(b:float):
    return b*2;
aaaa(2)

In [ ]:
b = np.zeros((4,4))
b[1][1] = 1
b[0:4][0:4]

In [13]:
aa

[[-0.6692138556101173], [1.5503418664414328], [-0.38547751246776496]]

In [17]:
    print(scad_render(cube([2,2,3])))




cube(size = [2, 2, 3]);


In [42]:
b = Rz(20)*Rx(10)*Rz(30)
zer = np.zeros((4,4))
zer = zer[3][3] + b
zer

matrix([[-0.69391103,  0.52135866, -0.49666149],
        [ 0.47913508,  0.84920153,  0.22200526],
        [ 0.53751006, -0.08391605, -0.83907153]])

In [69]:
b = Rz(20)*Rx(10)*Rz(30)
b

matrix([[-0.69391103,  0.52135866, -0.49666149],
        [ 0.47913508,  0.84920153,  0.22200526],
        [ 0.53751006, -0.08391605, -0.83907153]])

In [70]:
b = np.insert(b,[3],[[0],[0],[1]],axis=1)
b = np.insert(np.transpose(b),[3],[[0],[0],[0],[1]],axis=1)
b = np.transpose(b)
b

matrix([[-0.69391103,  0.52135866, -0.49666149,  0.        ],
        [ 0.47913508,  0.84920153,  0.22200526,  0.        ],
        [ 0.53751006, -0.08391605, -0.83907153,  1.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [61]:
b

matrix([[-0.69391103,  0.52135866, -0.49666149,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 1.        ,  1.        ,  1.        ,  1.        ],
        [ 0.47913508,  0.84920153,  0.22200526,  0.        ],
        [ 0.53751006, -0.08391605, -0.83907153,  1.        ]])